################################################################################
# training parameters
################################################################################
train:
  max_epochs: 450
  lr: 0.01              # sgd learning rate
  lr_min: 0.001       # min learning rate for cosing anneling shedule
  T_max: 30             # number of epoch before warm restart
  momentum: 0.9          # sgd momentum
  nesterov: True
  w_decay: 0.000        # weight decay
  batch_size: 3          # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: True    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  show_scans: False      # show scans during training
  workers: 1            # number of threads to get data

################################################################################
# backbone parameters
################################################################################
backbone:
  name: "dense_encoder"
  params:
    input_depth: 10
    drop_rate: 0.00
    bn_size: 4
    growth_rate: 8
    num_init_features: 128
    block_configuration: 
    - 6
    - 12
    - 24
  train: True # train backbone?

################################################################################
# decoder parameters
################################################################################
decoder:
  name: "dense_decoder"
  params:
    drop_rate: 0.00
    bn_size: 4
    growth_rate: 8
    block_configuration: 
    - 6
    - 6
    - 6
    - 6
    - 6
    - 3
  train: True # train decoder?

################################################################################
# classification head parameters
################################################################################
head:
  name: "prediction"
  train: True
  drop_rate: 0.00

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    max_range: 50
    img_prop:
      width: 1024
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16
